const CartActionTypes = {
  TOGGLE_CART_HIDDEN: "TOGGLE_CART_HIDDN",
  ADD_ITEM: "ADD_ITEM",
  CLEAR_ITEM_FROM_CART: "CLEAR_iTEM_FROM_CART",
  REDUCE_ITEM: "REDUCE_ITEM"
};
export default CartActionTypes;
